language: node_js
node_js:
  - "0.10"
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
  skip_cleanup: true
  local-dir: dist
  on:
    tags: true
after_success:
- echo "Deploying commit $TRAVIS_COMMIT"
